### ISSUE TITLE
Blank screen with Crosswalk

### ISSUE THREAD

**Issue by fmendoza** [obetomuniz/ionic-google-maps-starter#5]
Hi, like the title says, the map is showing only a black screen when using with crosswalk, any fix?

**Comment by obetomuniz** [comment]
Hi @fmendoza ...I not test the starter with Crosswalk yet, then I don't know if the plugin support it, for more details about the plugin used in this starter, can you check here: https://github.com/wf9a5m75/phonegap-googlemaps-plugin

**Comment by fmendoza** [comment]
It works, just need a little bit of configuration https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/536

**Comment by obetomuniz** [comment]
Cool tip @fmendoza . I'll put the link in my README.md as a suggestion.

Thanks for contribute.
