### ISSUE TITLE
Errors while npm install

### ISSUE THREAD

**Issue by victorantos** [obetomuniz/ionic-google-maps-starter#8]
36774 warn EPACKAGEJSON ionic-gmaps-starter@1.0.0 No repository field.
36775 warn EPACKAGEJSON ionic-gmaps-starter@1.0.0 No license field.
36776 verbose stack Error: node-sass@2.1.1 install: `node scripts/install.js`
36776 verbose stack Exit status 1
36776 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
36776 verbose stack     at emitTwo (events.js:87:13)
36776 verbose stack     at EventEmitter.emit (events.js:172:7)
36776 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
36776 verbose stack     at emitTwo (events.js:87:13)
36776 verbose stack     at ChildProcess.emit (events.js:172:7)
36776 verbose stack     at maybeClose (internal/child_process.js:821:16)
36776 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
36777 verbose pkgid node-sass@2.1.1
36778 verbose cwd C:\Users\victor\Source\Repos\ionic-google-maps-starter
36779 error Windows_NT 10.0.10586
36780 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
36781 error node v5.4.0
36782 error npm  v3.3.12
36783 error code ELIFECYCLE
36784 error node-sass@2.1.1 install: `node scripts/install.js`
36784 error Exit status 1
36785 error Failed at the node-sass@2.1.1 install script 'node scripts/install.js'.
36785 error Make sure you have the latest version of node.js and npm installed.
36785 error If you do, this is most likely a problem with the node-sass package,
36785 error not with npm itself.
36785 error Tell the author that this fails on your system:
36785 error     node scripts/install.js
36785 error You can get their info via:
36785 error     npm owner ls node-sass
36785 error There is likely additional logging output above.
36786 verbose exit [ 1, true ]

**Comment by obetomuniz** [comment]
Seems something related with `node-sass`, you solve it? I'll close the issue, but feel free to reopen.
