### ISSUE TITLE
outdated 'ionic-keyboard' plugin

### ISSUE THREAD

**Issue by arekKalbarczyk** [obetomuniz/ionic-google-maps-starter#9]
Hello,
I believe that cordova plugin `com.ionic.keyboard` could be substituted with `cordova-plugin-ionic-keyboard`.

**Comment by srinathvsp** [comment]
no just rename you try to install like cordova  plugin add ionic.plugin.keyboard

**Comment by obetomuniz** [comment]
Thanks for the answer @srinathvsp. Seems that @arekKalbarczyk fix the problem, once he doesn't return here to give a feedback.
